### ISSUE TITLE
Polkadot Vault. Dynamic Derivations. Can't import additional keys with "Main" key type.

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/nova-spektr#1434]
## Description

When user try to import additional keys via Import keyset feature, he can't import keys with "Main" type for additional networks

## Steps to Reproduce

1. Create Polkadot Vault with (Kusama, Polkadot, Westend) keys
2. Go to Wallet details
3. Try to import keyset with additional network - Zeitgeist with "Main" key type

## Expected Behavior
User can import additional keys

## Actual Behavior
Can't import, message is shown:
<img width="300" alt="Screenshot 2024-02-08 at 12 44 04" src="https://github.com/novasamatech/nova-spektr/assets/40560660/71124946-5133-4f3e-bae0-9036d87eabe7">

## Environment

- Operating system: macOS
- Version: upstream/baseline - 618c824476269ab2ad2ffc12b8813453ddae89a6

## Additional Information
Importing keyset:
```yaml
0x7a28037947ecebe0dd86dc0e910911cb33185fd0714b37b75943f67dcf9b6e7c:
  0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3:
    - key:
        derivation_path: "//polkadot"
        type: "main"
        name: "Main"
  0xb0a8d493285c2df73290dfb7e61f870f17b41801197a149ca93654499ea3dafe:
    - key:
        derivation_path: "//kusama"
        type: "main"
        name: "Main"
  0xe143f23803ac50e8f6f8e62695d1ce9e4e1d68aa36c1cd2cfd15340213f3423e:
    - key:
        derivation_path: "//westend"
        type: "main"
        name: "Main"
  0x1bf2a2ecb4a868de66ea8610f2ce7c8c43706561b6476031315f6640fe38e060:
    - key:
        derivation_path: "//kusama"
        type: "main"
        name: "Main wallet account"
version: "1"
```
database state:
<img width="300" alt="Screenshot 2024-02-08 at 12 47 21" src="https://github.com/novasamatech/nova-spektr/assets/40560660/94213c54-4725-4f4b-a45b-0ad93132b94a">
